- name: adding users 
  hosts: appserver
  become: yes
  tasks:
    - name: add users
      user: name='{{item}}'
      state: present
      with_items:
              - venkata
              - sai
              - krishna
